import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kalkulator Fee Admin Trading",
  description: "Generated by Topan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Kalkulator Fee Admin Trading</title>
      <meta
        name="google-site-verification"
        content="RGrUBpxFCkiIxHMtFwBF8JvaFL8xbjKtQJC7JxYmlVI"
      />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
